#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))  # noqa E402

from lsgtools import log
from lsgtools import cli
from lsgtools.virt.mshv import kernel

arg_parser = cli.create_arg_parser(prog="tag-validate",
                                   description="Kernel tag validation tool")
arg_parser.add_argument("tag", action="store")
args = arg_parser.parse_args()
log.set_verbosity(args.verbose)


tag_version = kernel.get_version_from_tag(args.tag)

if not kernel.is_version_valid(tag_version):
    log.error("Invalid tag name '{}'".format(args.tag))
    sys.exit(1)


mf_version = kernel.get_version_local()

if not tag_version == mf_version:
    log.err("Versions tag vs Makefile don't match: '{}' != '{}'".format(tag_version, mf_version))
    sys.exit(1)

log.msg("Tag '{}' is valid".format(args.tag))

sys.exit(0)
